"""Guards on the migration chain itself.

These caught a real bug: autogenerate drops tables but leaves their Postgres ENUM types
behind, so a downgrade followed by an upgrade failed with "type already exists".
"""

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from tests.conftest import _url_with_database, alembic_config, run_alembic


async def _scalars(url: str, sql: str) -> list[str]:
    engine = create_async_engine(url)
    try:
        async with engine.connect() as conn:
            return list((await conn.execute(text(sql))).scalars().all())
    finally:
        await engine.dispose()


def test_migration_chain_has_a_single_head() -> None:
    """Two heads means a merge was missed and `upgrade head` becomes ambiguous."""
    heads = ScriptDirectory.from_config(alembic_config("")).get_heads()
    assert len(heads) == 1, f"expected one head, found {heads}"


async def test_models_match_migrations(_migrated_database: str) -> None:
    """`alembic check` fails if a model changed without a matching migration."""
    try:
        await run_alembic(command.check, alembic_config(_migrated_database))
    except SystemExit as exc:  # alembic surfaces AutogenerateDiffsDetected as SystemExit
        pytest.fail(f"models have drifted from migrations: {exc}")


async def test_downgrade_then_upgrade_round_trips(_migrated_database: str) -> None:
    """A downgrade must leave the database genuinely empty, ENUM types included."""
    config = alembic_config(_migrated_database)
    await run_alembic(command.downgrade, config, "base")

    enums = await _scalars(_migrated_database, "SELECT typname FROM pg_type WHERE typtype = 'e'")
    tables = await _scalars(
        _migrated_database,
        "SELECT tablename FROM pg_tables WHERE schemaname = 'public' "
        "AND tablename <> 'alembic_version'",
    )
    # Restore before asserting, so a failure here doesn't strand the shared database.
    await run_alembic(command.upgrade, config, "head")

    assert enums == [], f"downgrade left ENUM types behind: {enums}"
    assert tables == [], f"downgrade left tables behind: {tables}"


async def test_schema_applies_to_an_empty_database(test_database_url: str) -> None:
    """Migrations must build the schema from nothing — the path a new environment takes."""
    admin_url = _url_with_database(test_database_url, "postgres")
    scratch_url = _url_with_database(test_database_url, "lgapp_scratch")

    admin = create_async_engine(admin_url, isolation_level="AUTOCOMMIT")
    async with admin.connect() as conn:
        await conn.exec_driver_sql("DROP DATABASE IF EXISTS lgapp_scratch WITH (FORCE)")
        await conn.exec_driver_sql("CREATE DATABASE lgapp_scratch")

    try:
        await run_alembic(command.upgrade, alembic_config(scratch_url), "head")
        tables = await _scalars(
            scratch_url, "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
        )
        assert {"decks", "cards", "users", "user_cards", "review_logs"} <= set(tables)
    finally:
        async with admin.connect() as conn:
            await conn.exec_driver_sql("DROP DATABASE IF EXISTS lgapp_scratch WITH (FORCE)")
        await admin.dispose()
