/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — checks the database round-trips */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List decks with the learner's progress */
        get: operations["list_decks_v1_decks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks/{deck_id}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe to a deck
         * @description Idempotent: re-subscribing picks up newly imported cards and leaves progress alone.
         */
        post: operations["subscribe_to_deck_v1_decks__deck_id__subscribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cards to review now */
        get: operations["get_queue_v1_reviews_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a batch of reviews
         * @description Record reviews and return the authoritative card states.
         *
         *     Accepts a batch because an offline client drains its outbox at once, and is
         *     idempotent on review id so a retry after a timeout cannot double-apply.
         */
        post: operations["post_reviews_v1_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress statistics */
        get: operations["get_stats_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardOut */
        CardOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** German */
            german: string;
            /** English */
            english: string;
            /** Part Of Speech */
            part_of_speech?: string | null;
            /** Article */
            article?: string | null;
            /** Plural */
            plural?: string | null;
            /** Example De */
            example_de?: string | null;
            /** Example En */
            example_en?: string | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * CardState
         * @description Mirrors FSRS's own card states; mapped in services/scheduler.py.
         * @enum {string}
         */
        CardState: "learning" | "review" | "relearning";
        /**
         * CardStateOut
         * @description Authoritative post-sync state. The client overwrites its local copy with this.
         */
        CardStateOut: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            state: components["schemas"]["CardState"];
            /**
             * Due
             * Format: date-time
             */
            due: string;
            /** Stability */
            stability?: number | null;
            /** Difficulty */
            difficulty?: number | null;
            /** Reps */
            reps: number;
            /** Lapses */
            lapses: number;
            /** Last Review */
            last_review?: string | null;
        };
        /** DayCount */
        DayCount: {
            /** Day */
            day: string;
            /** Count */
            count: number;
        };
        /** DeckOut */
        DeckOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Cefr Level */
            cefr_level?: string | null;
            /** Card Count */
            card_count: number;
            /** Subscribed */
            subscribed: boolean;
            /**
             * Due Count
             * @default 0
             */
            due_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QueueCardOut */
        QueueCardOut: {
            card: components["schemas"]["CardOut"];
            state: components["schemas"]["CardState"];
            /**
             * Due
             * Format: date-time
             */
            due: string;
            /** Reps */
            reps: number;
            /** Is New */
            is_new: boolean;
        };
        /** QueueOut */
        QueueOut: {
            /** Cards */
            cards: components["schemas"]["QueueCardOut"][];
            /** Due Total */
            due_total: number;
            /** New Remaining Today */
            new_remaining_today: number;
        };
        /**
         * Rating
         * @description FSRS grades. Stored as a smallint so ordering comparisons stay cheap.
         * @enum {integer}
         */
        Rating: 1 | 2 | 3 | 4;
        /** ReviewBatchIn */
        ReviewBatchIn: {
            /** Reviews */
            reviews: components["schemas"]["ReviewIn"][];
        };
        /** ReviewBatchOut */
        ReviewBatchOut: {
            /** Cards */
            cards: components["schemas"]["CardStateOut"][];
        };
        /**
         * ReviewIn
         * @description One review from the client.
         *
         *     `id` is generated client-side at review time so that a retry after a network failure
         *     carries the same id and is absorbed rather than double-counted. `reviewed_at` is when
         *     the learner actually answered, which for an offline review is well before we see it.
         */
        ReviewIn: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            rating: components["schemas"]["Rating"];
            /**
             * Reviewed At
             * Format: date-time
             */
            reviewed_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** StatsOut */
        StatsOut: {
            /** Reviews Total */
            reviews_total: number;
            /** Reviews Today */
            reviews_today: number;
            /**
             * Retention Rate
             * @description Share of mature reviews graded better than Again.
             */
            retention_rate?: number | null;
            /** Streak Days */
            streak_days: number;
            /** Cards By State */
            cards_by_state: {
                [key: string]: number;
            };
            /** Due Today */
            due_today: number;
            /** Reviews Per Day */
            reviews_per_day: components["schemas"]["DayCount"][];
        };
        /** SubscribeOut */
        SubscribeOut: {
            /**
             * Deck Id
             * Format: uuid
             */
            deck_id: string;
            /** Cards Added */
            cards_added: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_decks_v1_decks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckOut"][];
                };
            };
        };
    };
    subscribe_to_deck_v1_decks__deck_id__subscribe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscribeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queue_v1_reviews_queue_get: {
        parameters: {
            query?: {
                deck_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_reviews_v1_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
}
