"""initial schema

Revision ID: f9f85d11c290
Revises:
Create Date: 2026-07-14 09:11:29.397477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f9f85d11c290"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cefr_level", sa.String(length=2), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decks")),
        sa.UniqueConstraint("slug", name=op.f("uq_decks_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column("fsrs_parameters", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("desired_retention", sa.Float(), server_default="0.9", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "desired_retention > 0 AND desired_retention < 1",
            name=op.f("ck_users_desired_retention_is_a_probability"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deck_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("german", sa.Text(), nullable=False),
        sa.Column("english", sa.Text(), nullable=False),
        sa.Column("part_of_speech", sa.String(length=32), nullable=True),
        sa.Column("article", sa.String(length=8), nullable=True),
        sa.Column("plural", sa.Text(), nullable=True),
        sa.Column("example_de", sa.Text(), nullable=True),
        sa.Column("example_en", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"], ["decks.id"], name=op.f("fk_cards_deck_id_decks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
        sa.UniqueConstraint("deck_id", "external_id", name="uq_cards_deck_id_external_id"),
    )
    op.create_index("ix_cards_deck_id_position", "cards", ["deck_id", "position"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("deck_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "succeeded", "failed", name="import_status"),
            nullable=False,
        ),
        sa.Column("rows_read", sa.Integer(), nullable=False),
        sa.Column("rows_inserted", sa.Integer(), nullable=False),
        sa.Column("rows_updated", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'running') = (finished_at IS NULL)",
            name=op.f("ck_import_batches_finished_at_set_iff_not_running"),
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["decks.id"],
            name=op.f("fk_import_batches_deck_id_decks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_table(
        "user_decks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("deck_id", sa.UUID(), nullable=False),
        sa.Column("daily_new_limit", sa.Integer(), server_default="20", nullable=False),
        sa.Column("subscribed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"], ["decks.id"], name=op.f("fk_user_decks_deck_id_decks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_decks_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_decks")),
        sa.UniqueConstraint("user_id", "deck_id", name="uq_user_decks_user_id_deck_id"),
    )
    op.create_table(
        "review_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0",
            name=op.f("ck_review_logs_duration_is_non_negative"),
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 4", name=op.f("ck_review_logs_rating_within_fsrs_range")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_review_logs_card_id_cards"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_review_logs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_logs")),
    )
    op.create_index(
        "ix_review_logs_user_id_card_id_reviewed_at",
        "review_logs",
        ["user_id", "card_id", "reviewed_at"],
        unique=False,
    )
    op.create_index(
        "ix_review_logs_user_id_reviewed_at",
        "review_logs",
        ["user_id", "reviewed_at"],
        unique=False,
    )
    op.create_table(
        "user_cards",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("deck_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("learning", "review", "relearning", name="card_state"),
            server_default="learning",
            nullable=False,
        ),
        sa.Column("due", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("last_review", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reps", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lapses", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "difficulty IS NULL OR (difficulty >= 1 AND difficulty <= 10)",
            name=op.f("ck_user_cards_difficulty_within_fsrs_range"),
        ),
        sa.CheckConstraint(
            "stability IS NULL OR stability > 0", name=op.f("ck_user_cards_stability_is_positive")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_user_cards_card_id_cards"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"], ["decks.id"], name=op.f("fk_user_cards_deck_id_decks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_cards_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "card_id", name=op.f("pk_user_cards")),
    )
    op.create_index(
        "ix_user_cards_user_id_deck_id", "user_cards", ["user_id", "deck_id"], unique=False
    )
    op.create_index("ix_user_cards_user_id_due", "user_cards", ["user_id", "due"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_cards_user_id_due", table_name="user_cards")
    op.drop_index("ix_user_cards_user_id_deck_id", table_name="user_cards")
    op.drop_table("user_cards")
    op.drop_index("ix_review_logs_user_id_reviewed_at", table_name="review_logs")
    op.drop_index("ix_review_logs_user_id_card_id_reviewed_at", table_name="review_logs")
    op.drop_table("review_logs")
    op.drop_table("user_decks")
    op.drop_table("import_batches")
    op.drop_index("ix_cards_deck_id_position", table_name="cards")
    op.drop_table("cards")
    op.drop_table("users")
    op.drop_table("decks")
    # ### end Alembic commands ###

    # Autogenerate does not emit these: dropping a table leaves its ENUM type behind, so
    # without this a downgrade/upgrade round trip fails on "type already exists".
    sa.Enum(name="card_state").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="import_status").drop(op.get_bind(), checkfirst=True)
